Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -56,7 +56,6 @@ jobs:
       - name: Trigger Azure DevOps Build
         run: |
           echo "Triggering Azure DevOps build with definition ID ${{ github.event.inputs.azurePipelineDefinitionId }} using YAML file ${{ env.RESOURCE_YAML }}..."
-
           curl --http1.1 -v -X POST \
             -H "Authorization: Basic $(echo -n ":${{ secrets.AZURE_DEVOPS_TOKEN }}" | base64)" \
             -H "Content-Type: application/json" \
@@ -70,3 +69,13 @@ jobs:
                   }
                 }' \
             "https://dev.azure.com/${{ github.event.inputs.orgName }}/${{ github.event.inputs.projectName }}/_apis/build/builds?api-version=6.1-preview.6"
+
+      # Optional: Check if build was successfully triggered
+      - name: Check if build was triggered
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Build triggered successfully."
+          else
+            echo "Failed to trigger the build."
+            exit 1
+          fi
